spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/pokeJava
        username:
        password:
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show_sql: false
                format_sql: false
                use_sql_comments: false
        open-in-view: false

    main:
        banner-mode: off

springdoc:
    api-docs:
        path: /v3/api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
    packagesToScan: com.github.bladeehl.api

logging:
    config: classpath:logback-spring.xml
    pattern:
        console: none
