package com.github.bladeehl.model;

public enum InputType {
    TRAINER_MENU_CHOICE,
    TRAINER_NAME,
    TRAINER_INDEX,
    TRAINER_ACTION_CHOICE,
    CREATE_POKEMON_MENU,
    FIRST_POKEMON_INDEX,
    SECOND_POKEMON_INDEX,
    BATTLE_CHOICE,
    UPDATE_POKEMON_MENU,
    DELETE_POKEMON_INDEX
}
